"""add_intervention_status_types_and_update_interventions

Revision ID: 7c28deedac76
Revises: f6g7h8i9j0k1
Create Date: 2026-02-16 13:17:34.304435+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c28deedac76'
down_revision: Union[str, None] = 'f6g7h8i9j0k1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention_status_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('richiede_nota', sa.Boolean(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intervention_status_types'))
    )
    op.create_index(op.f('ix_intervention_status_types_codice'), 'intervention_status_types', ['codice'], unique=True)
    op.create_index(op.f('ix_intervention_status_types_id'), 'intervention_status_types', ['id'], unique=False)
    
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stato_intervento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('note_intervento', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('note_sospensione', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ore_effettive', sa.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('data_inizio', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('data_fine', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_interventions_stato_intervento_id', 'intervention_status_types', ['stato_intervento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_interventions_stato_intervento_id', type_='foreignkey')
        batch_op.drop_column('data_fine')
        batch_op.drop_column('data_inizio')
        batch_op.drop_column('ore_effettive')
        batch_op.drop_column('note_sospensione')
        batch_op.drop_column('note_intervento')
        batch_op.drop_column('stato_intervento_id')
    op.drop_index(op.f('ix_intervention_status_types_id'), table_name='intervention_status_types')
    op.drop_index(op.f('ix_intervention_status_types_codice'), table_name='intervention_status_types')
    op.drop_table('intervention_status_types')
    # ### end Alembic commands ###
