"""add work order audit table

Revision ID: 3e5b1c2f3a4b
Revises: 2d0da4a56402
Create Date: 2026-02-12 14:00:00.000000+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5b1c2f3a4b'
down_revision: Union[str, None] = '2d0da4a56402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.Enum('bozza', 'approvata', 'in lavorazione', 'completata', 'annullata', name='workorderstatus'), nullable=False),
    sa.Column('to_state', sa.Enum('bozza', 'approvata', 'in lavorazione', 'completata', 'annullata', name='workorderstatus'), nullable=False),
    sa.Column('transition_type', sa.Enum('manual', 'automatic', 'rollback', name='transitiontype'), nullable=False),
    sa.Column('executed_by', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_audits_created_at'), 'work_order_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_order_audits_work_order_id'), 'work_order_audits', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_audits_work_order_id'), table_name='work_order_audits')
    op.drop_index(op.f('ix_work_order_audits_created_at'), table_name='work_order_audits')
    op.drop_table('work_order_audits')
    # ### end Alembic commands ###
