"""add data_compilazione to work_orders

Revision ID: 2d0da4a56402
Revises: 
Create Date: 2026-02-11 20:30:45.997855+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0da4a56402'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('data_compilazione', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_work_orders_data_compilazione'), 'work_orders', ['data_compilazione'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_data_compilazione'), table_name='work_orders')
    op.drop_column('work_orders', 'data_compilazione')
    # ### end Alembic commands ###
