"""add_vehicle_technical_fields

Revision ID: 0a9f58f7b282
Revises: 7c28deedac76
Create Date: 2026-02-16 15:25:51.164127+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9f58f7b282'
down_revision: Union[str, None] = '7c28deedac76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nota: SQLite non supporta ALTER constraints, quindi la FK per interventions
    # è già stata creata con la colonna nella migrazione precedente
    op.add_column('vehicles', sa.Column('cilindrata', sa.String(length=20), nullable=True))
    op.add_column('vehicles', sa.Column('kw', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('cv', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('porte', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('carburante', sa.String(length=30), nullable=True))
    op.add_column('vehicles', sa.Column('prima_immatricolazione', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'prima_immatricolazione')
    op.drop_column('vehicles', 'carburante')
    op.drop_column('vehicles', 'porte')
    op.drop_column('vehicles', 'cv')
    op.drop_column('vehicles', 'kw')
    op.drop_column('vehicles', 'cilindrata')
    # ### end Alembic commands ###
